/*
 * generated by Xtext
 */
package at.tugraz.xtext.restrictionframework;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RestrictionFrameworkUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return at.tugraz.xtext.restrictionframework.ui.internal.RestrictionFrameworkActivator.getInstance().getInjector("at.tugraz.xtext.restrictionframework.RestrictionFramework");
	}
	
}
