/*
 * generated by Xtext
 */
package at.tugraz.xtext.metamodel.ui.contentassist

import at.tugraz.xtext.metamodel.ui.contentassist.AbstractMetamodelProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class MetamodelProposalProvider extends AbstractMetamodelProposalProvider {
}
