/*
 * generated by Xtext
 */
package at.tugraz.xtext.metamodel.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractMetamodelValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(at.tugraz.xtext.metamodel.metamodel.MetamodelPackage.eINSTANCE);
		return result;
	}
}
