/*
 * generated by Xtext
 */
package at.tugraz.xtext.metamodel;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MetamodelRuntimeModule extends at.tugraz.xtext.metamodel.AbstractMetamodelRuntimeModule {

}
