/*
 * generated by Xtext
 */
package at.tugraz.xtext.metamodel;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MetamodelStandaloneSetup extends MetamodelStandaloneSetupGenerated{

	public static void doSetup() {
		new MetamodelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

