/*
 * generated by Xtext
 */
package at.tugraz.xtext.restrictionframework.ui.contentassist

import at.tugraz.xtext.restrictionframework.ui.contentassist.AbstractRestrictionFrameworkProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class RestrictionFrameworkProposalProvider extends AbstractRestrictionFrameworkProposalProvider {
}
