/*
 * generated by Xtext
 */
package at.tugraz.xtext.metamodel.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class MetamodelGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class DomainmodelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Domainmodel");
		private final Assignment cElementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cElementsAbstractElementParserRuleCall_0 = (RuleCall)cElementsAssignment.eContents().get(0);
		
		/// * TODOS
		// * function generator
		// * unique function IDs
		// * / Domainmodel:
		//	elements+=AbstractElement*;
		@Override public ParserRule getRule() { return rule; }

		//elements+=AbstractElement*
		public Assignment getElementsAssignment() { return cElementsAssignment; }

		//AbstractElement
		public RuleCall getElementsAbstractElementParserRuleCall_0() { return cElementsAbstractElementParserRuleCall_0; }
	}

	public class AbstractElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AbstractElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTypeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFunctionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//AbstractElement:
		//	Type | Function;
		@Override public ParserRule getRule() { return rule; }

		//Type | Function
		public Alternatives getAlternatives() { return cAlternatives; }

		//Type
		public RuleCall getTypeParserRuleCall_0() { return cTypeParserRuleCall_0; }

		//Function
		public RuleCall getFunctionParserRuleCall_1() { return cFunctionParserRuleCall_1; }
	}

	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cDatatypeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cObjectParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Type:
		//	Datatype | //| SecureObject
		//	Object;
		@Override public ParserRule getRule() { return rule; }

		//Datatype | //| SecureObject
		//Object
		public Alternatives getAlternatives() { return cAlternatives; }

		//Datatype
		public RuleCall getDatatypeParserRuleCall_0() { return cDatatypeParserRuleCall_0; }

		////| SecureObject
		//Object
		public RuleCall getObjectParserRuleCall_1() { return cObjectParserRuleCall_1; }
	}

	public class FunctionTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cRepeatAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cRepeatRepeatKeyword_0_0 = (Keyword)cRepeatAssignment_0.eContents().get(0);
		private final Assignment cOptionalAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cOptionalOptionalKeyword_1_0 = (Keyword)cOptionalAssignment_1.eContents().get(0);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cTypeTypeCrossReference_2_0 = (CrossReference)cTypeAssignment_2.eContents().get(0);
		private final RuleCall cTypeTypeIDTerminalRuleCall_2_0_1 = (RuleCall)cTypeTypeCrossReference_2_0.eContents().get(1);
		
		////TODO in generator einbauen
		//FunctionType:
		//	repeat?="repeat"? optional?="optional"? Type=[Type];
		@Override public ParserRule getRule() { return rule; }

		//repeat?="repeat"? optional?="optional"? Type=[Type]
		public Group getGroup() { return cGroup; }

		//repeat?="repeat"?
		public Assignment getRepeatAssignment_0() { return cRepeatAssignment_0; }

		//"repeat"
		public Keyword getRepeatRepeatKeyword_0_0() { return cRepeatRepeatKeyword_0_0; }

		//optional?="optional"?
		public Assignment getOptionalAssignment_1() { return cOptionalAssignment_1; }

		//"optional"
		public Keyword getOptionalOptionalKeyword_1_0() { return cOptionalOptionalKeyword_1_0; }

		//Type=[Type]
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }

		//[Type]
		public CrossReference getTypeTypeCrossReference_2_0() { return cTypeTypeCrossReference_2_0; }

		//ID
		public RuleCall getTypeTypeIDTerminalRuleCall_2_0_1() { return cTypeTypeIDTerminalRuleCall_2_0_1; }
	}

	public class DatatypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Datatype");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDatatypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cTypeAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cTypeSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cTypeAssignment_2_1.eContents().get(0);
		private final Group cGroup_2_2 = (Group)cGroup_2.eContents().get(2);
		private final Keyword cDefaultvalueKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Assignment cDefaultValueAssignment_2_2_1 = (Assignment)cGroup_2_2.eContents().get(1);
		private final RuleCall cDefaultValueSTRINGTerminalRuleCall_2_2_1_0 = (RuleCall)cDefaultValueAssignment_2_2_1.eContents().get(0);
		private final Assignment cRestrictionsAssignment_2_3 = (Assignment)cGroup_2.eContents().get(3);
		private final RuleCall cRestrictionsRestrictionParserRuleCall_2_3_0 = (RuleCall)cRestrictionsAssignment_2_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		
		//Datatype:
		//	"datatype" name=ID ("{" type=STRING ("defaultvalue=" defaultValue=STRING)? //TODO Will ich das?
		//	restrictions+=Restriction* "}")?;
		@Override public ParserRule getRule() { return rule; }

		//"datatype" name=ID ("{" type=STRING ("defaultvalue=" defaultValue=STRING)? //TODO Will ich das?
		//restrictions+=Restriction* "}")?
		public Group getGroup() { return cGroup; }

		//"datatype"
		public Keyword getDatatypeKeyword_0() { return cDatatypeKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//("{" type=STRING ("defaultvalue=" defaultValue=STRING)? //TODO Will ich das?
		//restrictions+=Restriction* "}")?
		public Group getGroup_2() { return cGroup_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }

		//type=STRING
		public Assignment getTypeAssignment_2_1() { return cTypeAssignment_2_1; }

		//STRING
		public RuleCall getTypeSTRINGTerminalRuleCall_2_1_0() { return cTypeSTRINGTerminalRuleCall_2_1_0; }

		//("defaultvalue=" defaultValue=STRING)?
		public Group getGroup_2_2() { return cGroup_2_2; }

		//"defaultvalue="
		public Keyword getDefaultvalueKeyword_2_2_0() { return cDefaultvalueKeyword_2_2_0; }

		//defaultValue=STRING
		public Assignment getDefaultValueAssignment_2_2_1() { return cDefaultValueAssignment_2_2_1; }

		//STRING
		public RuleCall getDefaultValueSTRINGTerminalRuleCall_2_2_1_0() { return cDefaultValueSTRINGTerminalRuleCall_2_2_1_0; }

		//restrictions+=Restriction*
		public Assignment getRestrictionsAssignment_2_3() { return cRestrictionsAssignment_2_3; }

		//Restriction
		public RuleCall getRestrictionsRestrictionParserRuleCall_2_3_0() { return cRestrictionsRestrictionParserRuleCall_2_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_2_4() { return cRightCurlyBracketKeyword_2_4; }
	}

	public class RestrictionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Restriction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Assignment cStringrestrictionAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final Keyword cStringrestrictionStringrestrictionKeyword_0_0_0 = (Keyword)cStringrestrictionAssignment_0_0.eContents().get(0);
		private final Group cGroup_0_1 = (Group)cGroup_0.eContents().get(1);
		private final Keyword cMaxlengthKeyword_0_1_0 = (Keyword)cGroup_0_1.eContents().get(0);
		private final Assignment cMaxlengthAssignment_0_1_1 = (Assignment)cGroup_0_1.eContents().get(1);
		private final RuleCall cMaxlengthINTTerminalRuleCall_0_1_1_0 = (RuleCall)cMaxlengthAssignment_0_1_1.eContents().get(0);
		private final Keyword cMinlengthKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Assignment cMinlengthAssignment_0_3 = (Assignment)cGroup_0.eContents().get(3);
		private final RuleCall cMinlengthINTTerminalRuleCall_0_3_0 = (RuleCall)cMinlengthAssignment_0_3.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cValuerestrictionAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final Keyword cValuerestrictionValuerestricionKeyword_1_0_0 = (Keyword)cValuerestrictionAssignment_1_0.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final Keyword cMaxvalueKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Assignment cMaxvalueAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final RuleCall cMaxvalueINTTerminalRuleCall_1_1_1_0 = (RuleCall)cMaxvalueAssignment_1_1_1.eContents().get(0);
		private final Keyword cMinvalueKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Assignment cMinvalueAssignment_1_3 = (Assignment)cGroup_1.eContents().get(3);
		private final RuleCall cMinvalueINTTerminalRuleCall_1_3_0 = (RuleCall)cMinvalueAssignment_1_3.eContents().get(0);
		
		//Restriction:
		//	stringrestriction?="stringrestriction" ("maxlength" maxlength=INT)? "minlength" minlength=INT |
		//	valuerestriction?="valuerestricion" ("maxvalue" maxvalue=INT)? "minvalue" minvalue=INT;
		@Override public ParserRule getRule() { return rule; }

		//stringrestriction?="stringrestriction" ("maxlength" maxlength=INT)? "minlength" minlength=INT |
		//valuerestriction?="valuerestricion" ("maxvalue" maxvalue=INT)? "minvalue" minvalue=INT
		public Alternatives getAlternatives() { return cAlternatives; }

		//stringrestriction?="stringrestriction" ("maxlength" maxlength=INT)? "minlength" minlength=INT
		public Group getGroup_0() { return cGroup_0; }

		//stringrestriction?="stringrestriction"
		public Assignment getStringrestrictionAssignment_0_0() { return cStringrestrictionAssignment_0_0; }

		//"stringrestriction"
		public Keyword getStringrestrictionStringrestrictionKeyword_0_0_0() { return cStringrestrictionStringrestrictionKeyword_0_0_0; }

		//("maxlength" maxlength=INT)?
		public Group getGroup_0_1() { return cGroup_0_1; }

		//"maxlength"
		public Keyword getMaxlengthKeyword_0_1_0() { return cMaxlengthKeyword_0_1_0; }

		//maxlength=INT
		public Assignment getMaxlengthAssignment_0_1_1() { return cMaxlengthAssignment_0_1_1; }

		//INT
		public RuleCall getMaxlengthINTTerminalRuleCall_0_1_1_0() { return cMaxlengthINTTerminalRuleCall_0_1_1_0; }

		//"minlength"
		public Keyword getMinlengthKeyword_0_2() { return cMinlengthKeyword_0_2; }

		//minlength=INT
		public Assignment getMinlengthAssignment_0_3() { return cMinlengthAssignment_0_3; }

		//INT
		public RuleCall getMinlengthINTTerminalRuleCall_0_3_0() { return cMinlengthINTTerminalRuleCall_0_3_0; }

		//valuerestriction?="valuerestricion" ("maxvalue" maxvalue=INT)? "minvalue" minvalue=INT
		public Group getGroup_1() { return cGroup_1; }

		//valuerestriction?="valuerestricion"
		public Assignment getValuerestrictionAssignment_1_0() { return cValuerestrictionAssignment_1_0; }

		//"valuerestricion"
		public Keyword getValuerestrictionValuerestricionKeyword_1_0_0() { return cValuerestrictionValuerestricionKeyword_1_0_0; }

		//("maxvalue" maxvalue=INT)?
		public Group getGroup_1_1() { return cGroup_1_1; }

		//"maxvalue"
		public Keyword getMaxvalueKeyword_1_1_0() { return cMaxvalueKeyword_1_1_0; }

		//maxvalue=INT
		public Assignment getMaxvalueAssignment_1_1_1() { return cMaxvalueAssignment_1_1_1; }

		//INT
		public RuleCall getMaxvalueINTTerminalRuleCall_1_1_1_0() { return cMaxvalueINTTerminalRuleCall_1_1_1_0; }

		//"minvalue"
		public Keyword getMinvalueKeyword_1_2() { return cMinvalueKeyword_1_2; }

		//minvalue=INT
		public Assignment getMinvalueAssignment_1_3() { return cMinvalueAssignment_1_3; }

		//INT
		public RuleCall getMinvalueINTTerminalRuleCall_1_3_0() { return cMinvalueINTTerminalRuleCall_1_3_0; }
	}

	public class MemberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Member");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cTypeTypeCrossReference_2_0 = (CrossReference)cTypeAssignment_2.eContents().get(0);
		private final RuleCall cTypeTypeIDTerminalRuleCall_2_0_1 = (RuleCall)cTypeTypeCrossReference_2_0.eContents().get(1);
		
		////StringRestriction:
		////	("maxlength" maxlength = INT)?
		////	"minlength" minlength = INT
		////	
		////;
		////
		////ValueRestriction:
		////	("maxvalue" maxvalue = INT)?
		////	"minvalue" minvalue = INT
		////	
		////;
		////SecureObject:
		////	"object" name = ID "{"
		////		(members += Member)*
		////	"}"
		////;
		//Member:
		//	name=ID ":" type=[Type];
		@Override public ParserRule getRule() { return rule; }

		//name=ID ":" type=[Type]
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }

		//type=[Type]
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }

		//[Type]
		public CrossReference getTypeTypeCrossReference_2_0() { return cTypeTypeCrossReference_2_0; }

		//ID
		public RuleCall getTypeTypeIDTerminalRuleCall_2_0_1() { return cTypeTypeIDTerminalRuleCall_2_0_1; }
	}

	public class ObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Object");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cObjectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cExtendsKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cSuperTypeAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cSuperTypeObjectCrossReference_2_1_0 = (CrossReference)cSuperTypeAssignment_2_1.eContents().get(0);
		private final RuleCall cSuperTypeObjectIDTerminalRuleCall_2_1_0_1 = (RuleCall)cSuperTypeObjectCrossReference_2_1_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cMembersAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cMembersMemberParserRuleCall_4_0_0 = (RuleCall)cMembersAssignment_4_0.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cGroup_4.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Assignment cRestrictionsAssignment_4_1_1 = (Assignment)cGroup_4_1.eContents().get(1);
		private final RuleCall cRestrictionsRestrictionParserRuleCall_4_1_1_0 = (RuleCall)cRestrictionsAssignment_4_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_1_2 = (Keyword)cGroup_4_1.eContents().get(2);
		private final Assignment cIssecureAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final Keyword cIssecureIssecureKeyword_5_0 = (Keyword)cIssecureAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Object:
		//	"object" name=ID ("extends" superType=[Object])? "{" (members+=Member ("{" restrictions+=Restriction "}")?)*
		//	issecure?="issecure"? "}";
		@Override public ParserRule getRule() { return rule; }

		//"object" name=ID ("extends" superType=[Object])? "{" (members+=Member ("{" restrictions+=Restriction "}")?)*
		//issecure?="issecure"? "}"
		public Group getGroup() { return cGroup; }

		//"object"
		public Keyword getObjectKeyword_0() { return cObjectKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//("extends" superType=[Object])?
		public Group getGroup_2() { return cGroup_2; }

		//"extends"
		public Keyword getExtendsKeyword_2_0() { return cExtendsKeyword_2_0; }

		//superType=[Object]
		public Assignment getSuperTypeAssignment_2_1() { return cSuperTypeAssignment_2_1; }

		//[Object]
		public CrossReference getSuperTypeObjectCrossReference_2_1_0() { return cSuperTypeObjectCrossReference_2_1_0; }

		//ID
		public RuleCall getSuperTypeObjectIDTerminalRuleCall_2_1_0_1() { return cSuperTypeObjectIDTerminalRuleCall_2_1_0_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//(members+=Member ("{" restrictions+=Restriction "}")?)*
		public Group getGroup_4() { return cGroup_4; }

		//members+=Member
		public Assignment getMembersAssignment_4_0() { return cMembersAssignment_4_0; }

		//Member
		public RuleCall getMembersMemberParserRuleCall_4_0_0() { return cMembersMemberParserRuleCall_4_0_0; }

		//("{" restrictions+=Restriction "}")?
		public Group getGroup_4_1() { return cGroup_4_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1_0() { return cLeftCurlyBracketKeyword_4_1_0; }

		//restrictions+=Restriction
		public Assignment getRestrictionsAssignment_4_1_1() { return cRestrictionsAssignment_4_1_1; }

		//Restriction
		public RuleCall getRestrictionsRestrictionParserRuleCall_4_1_1_0() { return cRestrictionsRestrictionParserRuleCall_4_1_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_1_2() { return cRightCurlyBracketKeyword_4_1_2; }

		//issecure?="issecure"?
		public Assignment getIssecureAssignment_5() { return cIssecureAssignment_5; }

		//"issecure"
		public Keyword getIssecureIssecureKeyword_5_0() { return cIssecureIssecureKeyword_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class FunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Function");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFunctionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cExtendsKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cSuperTypeAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cSuperTypeObjectCrossReference_2_1_0 = (CrossReference)cSuperTypeAssignment_2_1.eContents().get(0);
		private final RuleCall cSuperTypeObjectIDTerminalRuleCall_2_1_0_1 = (RuleCall)cSuperTypeObjectCrossReference_2_1_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cIdKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cIdentifierAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cIdentifierINTTerminalRuleCall_5_0 = (RuleCall)cIdentifierAssignment_5.eContents().get(0);
		private final Assignment cIssecureAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final Keyword cIssecureIssecureKeyword_6_0 = (Keyword)cIssecureAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cGetsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cInputsAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cInputsFunctionTypeParserRuleCall_7_1_0 = (RuleCall)cInputsAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cReturnsKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cOutpustAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cOutpustFunctionTypeParserRuleCall_8_1_0 = (RuleCall)cOutpustAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Function:
		//	"function" name=ID ("extends" superType=[Object])? "{" "id" identifier= //TODO unique prüfen
		//	INT issecure?="issecure"? ("gets" inputs+=FunctionType*)? ("returns" outpust+=FunctionType*)? "}";
		@Override public ParserRule getRule() { return rule; }

		//"function" name=ID ("extends" superType=[Object])? "{" "id" identifier= //TODO unique prüfen
		//INT issecure?="issecure"? ("gets" inputs+=FunctionType*)? ("returns" outpust+=FunctionType*)? "}"
		public Group getGroup() { return cGroup; }

		//"function"
		public Keyword getFunctionKeyword_0() { return cFunctionKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//("extends" superType=[Object])?
		public Group getGroup_2() { return cGroup_2; }

		//"extends"
		public Keyword getExtendsKeyword_2_0() { return cExtendsKeyword_2_0; }

		//superType=[Object]
		public Assignment getSuperTypeAssignment_2_1() { return cSuperTypeAssignment_2_1; }

		//[Object]
		public CrossReference getSuperTypeObjectCrossReference_2_1_0() { return cSuperTypeObjectCrossReference_2_1_0; }

		//ID
		public RuleCall getSuperTypeObjectIDTerminalRuleCall_2_1_0_1() { return cSuperTypeObjectIDTerminalRuleCall_2_1_0_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//"id"
		public Keyword getIdKeyword_4() { return cIdKeyword_4; }

		//identifier= //TODO unique prüfen
		//INT
		public Assignment getIdentifierAssignment_5() { return cIdentifierAssignment_5; }

		////TODO unique prüfen
		//INT
		public RuleCall getIdentifierINTTerminalRuleCall_5_0() { return cIdentifierINTTerminalRuleCall_5_0; }

		//issecure?="issecure"?
		public Assignment getIssecureAssignment_6() { return cIssecureAssignment_6; }

		//"issecure"
		public Keyword getIssecureIssecureKeyword_6_0() { return cIssecureIssecureKeyword_6_0; }

		//("gets" inputs+=FunctionType*)?
		public Group getGroup_7() { return cGroup_7; }

		//"gets"
		public Keyword getGetsKeyword_7_0() { return cGetsKeyword_7_0; }

		//inputs+=FunctionType*
		public Assignment getInputsAssignment_7_1() { return cInputsAssignment_7_1; }

		//FunctionType
		public RuleCall getInputsFunctionTypeParserRuleCall_7_1_0() { return cInputsFunctionTypeParserRuleCall_7_1_0; }

		//("returns" outpust+=FunctionType*)?
		public Group getGroup_8() { return cGroup_8; }

		//"returns"
		public Keyword getReturnsKeyword_8_0() { return cReturnsKeyword_8_0; }

		//outpust+=FunctionType*
		public Assignment getOutpustAssignment_8_1() { return cOutpustAssignment_8_1; }

		//FunctionType
		public RuleCall getOutpustFunctionTypeParserRuleCall_8_1_0() { return cOutpustFunctionTypeParserRuleCall_8_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	
	
	private final DomainmodelElements pDomainmodel;
	private final AbstractElementElements pAbstractElement;
	private final TypeElements pType;
	private final FunctionTypeElements pFunctionType;
	private final DatatypeElements pDatatype;
	private final RestrictionElements pRestriction;
	private final MemberElements pMember;
	private final ObjectElements pObject;
	private final FunctionElements pFunction;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MetamodelGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pDomainmodel = new DomainmodelElements();
		this.pAbstractElement = new AbstractElementElements();
		this.pType = new TypeElements();
		this.pFunctionType = new FunctionTypeElements();
		this.pDatatype = new DatatypeElements();
		this.pRestriction = new RestrictionElements();
		this.pMember = new MemberElements();
		this.pObject = new ObjectElements();
		this.pFunction = new FunctionElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("at.tugraz.xtext.metamodel.Metamodel".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	/// * TODOS
	// * function generator
	// * unique function IDs
	// * / Domainmodel:
	//	elements+=AbstractElement*;
	public DomainmodelElements getDomainmodelAccess() {
		return pDomainmodel;
	}
	
	public ParserRule getDomainmodelRule() {
		return getDomainmodelAccess().getRule();
	}

	//AbstractElement:
	//	Type | Function;
	public AbstractElementElements getAbstractElementAccess() {
		return pAbstractElement;
	}
	
	public ParserRule getAbstractElementRule() {
		return getAbstractElementAccess().getRule();
	}

	//Type:
	//	Datatype | //| SecureObject
	//	Object;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}

	////TODO in generator einbauen
	//FunctionType:
	//	repeat?="repeat"? optional?="optional"? Type=[Type];
	public FunctionTypeElements getFunctionTypeAccess() {
		return pFunctionType;
	}
	
	public ParserRule getFunctionTypeRule() {
		return getFunctionTypeAccess().getRule();
	}

	//Datatype:
	//	"datatype" name=ID ("{" type=STRING ("defaultvalue=" defaultValue=STRING)? //TODO Will ich das?
	//	restrictions+=Restriction* "}")?;
	public DatatypeElements getDatatypeAccess() {
		return pDatatype;
	}
	
	public ParserRule getDatatypeRule() {
		return getDatatypeAccess().getRule();
	}

	//Restriction:
	//	stringrestriction?="stringrestriction" ("maxlength" maxlength=INT)? "minlength" minlength=INT |
	//	valuerestriction?="valuerestricion" ("maxvalue" maxvalue=INT)? "minvalue" minvalue=INT;
	public RestrictionElements getRestrictionAccess() {
		return pRestriction;
	}
	
	public ParserRule getRestrictionRule() {
		return getRestrictionAccess().getRule();
	}

	////StringRestriction:
	////	("maxlength" maxlength = INT)?
	////	"minlength" minlength = INT
	////	
	////;
	////
	////ValueRestriction:
	////	("maxvalue" maxvalue = INT)?
	////	"minvalue" minvalue = INT
	////	
	////;
	////SecureObject:
	////	"object" name = ID "{"
	////		(members += Member)*
	////	"}"
	////;
	//Member:
	//	name=ID ":" type=[Type];
	public MemberElements getMemberAccess() {
		return pMember;
	}
	
	public ParserRule getMemberRule() {
		return getMemberAccess().getRule();
	}

	//Object:
	//	"object" name=ID ("extends" superType=[Object])? "{" (members+=Member ("{" restrictions+=Restriction "}")?)*
	//	issecure?="issecure"? "}";
	public ObjectElements getObjectAccess() {
		return pObject;
	}
	
	public ParserRule getObjectRule() {
		return getObjectAccess().getRule();
	}

	//Function:
	//	"function" name=ID ("extends" superType=[Object])? "{" "id" identifier= //TODO unique prüfen
	//	INT issecure?="issecure"? ("gets" inputs+=FunctionType*)? ("returns" outpust+=FunctionType*)? "}";
	public FunctionElements getFunctionAccess() {
		return pFunction;
	}
	
	public ParserRule getFunctionRule() {
		return getFunctionAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
