/*
 * generated by Xtext
 */
package at.tugraz.xtext.metamodel.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import at.tugraz.xtext.metamodel.ui.internal.MetamodelActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MetamodelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MetamodelActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MetamodelActivator.getInstance().getInjector(MetamodelActivator.AT_TUGRAZ_XTEXT_METAMODEL_METAMODEL);
	}
	
}
