/*
 * generated by Xtext
 */
package at.tugraz.xtext.restrictionframework.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.tugraz.xtext.restrictionframework.services.RestrictionFrameworkGrammarAccess;

public class RestrictionFrameworkParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RestrictionFrameworkGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.tugraz.xtext.restrictionframework.parser.antlr.internal.InternalRestrictionFrameworkParser createParser(XtextTokenStream stream) {
		return new at.tugraz.xtext.restrictionframework.parser.antlr.internal.InternalRestrictionFrameworkParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public RestrictionFrameworkGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RestrictionFrameworkGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
