/*
 * generated by Xtext
 */
package at.tugraz.xtext.restrictionframework.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RestrictionFrameworkAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("at/tugraz/xtext/restrictionframework/parser/antlr/internal/InternalRestrictionFramework.tokens");
	}
}
