/*
 * generated by Xtext
 */
package at.tugraz.xtext.restrictionframework.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RestrictionFrameworkUiModule extends at.tugraz.xtext.restrictionframework.ui.AbstractRestrictionFrameworkUiModule {
	public RestrictionFrameworkUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
