/*
 * generated by Xtext
 */
package at.tugraz.xtext.metamodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MetamodelUiModule extends at.tugraz.xtext.metamodel.ui.AbstractMetamodelUiModule {
	public MetamodelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
