/*
 * generated by Xtext
 */
package at.tugraz.xtext.restrictionframework.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import at.tugraz.xtext.restrictionframework.ui.internal.RestrictionFrameworkActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RestrictionFrameworkExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RestrictionFrameworkActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RestrictionFrameworkActivator.getInstance().getInjector(RestrictionFrameworkActivator.AT_TUGRAZ_XTEXT_RESTRICTIONFRAMEWORK_RESTRICTIONFRAMEWORK);
	}
	
}
