/*
 * generated by Xtext
 */
package at.tugraz.xtext.metamodel.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MetamodelAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("at/tugraz/xtext/metamodel/parser/antlr/internal/InternalMetamodel.tokens");
	}
}
