/*
 * generated by Xtext
 */
package at.tugraz.xtext.restrictionframework;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RestrictionFrameworkStandaloneSetup extends RestrictionFrameworkStandaloneSetupGenerated{

	public static void doSetup() {
		new RestrictionFrameworkStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

