/*
 * generated by Xtext
 */
package at.tugraz.xtext.restrictionframework;

import org.eclipse.xtext.generator.IGenerator;
import at.tugraz.xtext.restrictionframework.generator.RestrictionFrameworkGenerator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RestrictionFrameworkRuntimeModule extends at.tugraz.xtext.restrictionframework.AbstractRestrictionFrameworkRuntimeModule {

	
	public Class<? extends IGenerator> bindIGenerator() {
        return RestrictionFrameworkGenerator.class;
    }
}