/*
 * generated by Xtext
 */
package at.tugraz.xtext.restrictionframework;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RestrictionFrameworkRuntimeModule extends at.tugraz.xtext.restrictionframework.AbstractRestrictionFrameworkRuntimeModule {

}
